import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import { Toaster, toast } from "sonner";
import { NextUIProvider } from "@nextui-org/react";
import AuthProvider from "./components/AuthProvider";
const eB_Garamond = EB_Garamond({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />
      <body className={eB_Garamond.className}>
        <main>
          <NextUIProvider>
            <AuthProvider>{children}</AuthProvider>
          </NextUIProvider>
        </main>
      </body>
    </html>
  );
}
